-- DEFINING VARIABLES FOR LOOP
-- DECLARE @EXAMPLE_VARIABLE AS INT
             
   DECLARE EXAMPLE_CURSOR_NAME CURSOR
   
FOR
     -- HERE DEFINING QUERY FOR LOOP
    
OPEN EXAMPLE_CURSOR_NAME
           
 FETCH NEXT FROM EXAMPLE_CURSOR_NAME INTO -- @EXAMPLE_VARIABLE
                         
WHILE @@FETCH_STATUS = 0
BEGIN
    
    -- HERE FOR WHAT YOU WANT IN LOOP
    
    FETCH NEXT FROM EXAMPLE_CURSOR_NAME  INTO --@EXAMPLE_VARIABLE
END
                  
CLOSE EXAMPLE_CURSOR_NAME 
DEALLOCATE EXAMPLE_CURSOR_NAME 
